### PR TITLE
Export more types from index.d.ts

### LINKED ISSUE #617: Export DayPickerProps (and more?) from @types/react-day-picker
It appears `DayPickerProps` is not explicitly exported from `@types/react-day-picker`. You can reach into it by importing a submodule:

```tsx
import { DayPickerProps } from "@types/react-day-picker/props"
```

But this is hacky and produces a lint error when `tslint`'s [`no-submodule-imports`](https://palantir.github.io/tslint/rules/no-submodule-imports/) rule is enabled. The workaround is to disable the rule for the import statement in question:

```tsx
// tslint:disable-next-line:no-submodule-imports
import { DayPickerProps } from "@types/react-day-picker/props";
```

This is a **`P3`** since we have a workaround, but it would be nice to have all types exported from `index.d.ts`, rather than exporting only `DayPicker`.

**EDIT:**
I may have the package name wrong (I haven't tried this myself - I'm following along in another PR as a reviewer). Are the types just exported from `react-day-picker` directly, or are they published under `@types/react-day-picker`? Either way, my request stands!

### PR DESCRIPTION
**Pull request by adidahiya**
Fixes #617

### CODE REVIEW

File: types/index.d.ts [hunk 1]
```diff
@@ -2,3 +2,6 @@
 
 import DayPicker from './DayPicker';
 export default DayPicker;
+
```
Comment (i8wu) [inline types/index.d.ts]: if you add `export * from './DayPickerInput';` it'll also solve https://github.com/gpbl/react-day-picker/issues/586

Comment (adidahiya) [reply types/index.d.ts]: that is semantically incorrect. DayPickerInput is not exported from the root of the package: https://github.com/gpbl/react-day-picker/blob/master/DayPicker.js

Comment (i8wu) [reply types/index.d.ts]: Hm, what would be the correct way then? Kinda new to typescript.

Comment (adidahiya) [reply types/index.d.ts]: since the JS export is from a submodule, you can import in typescript like this:

```ts
import { DayPickerInput } from "react-day-picker/DayPickerInput";
```

that's why [`types/DayPickerInput.d.ts`](https://github.com/gpbl/react-day-picker/blob/master/types/DayPickerInput.d.ts) exists.

Comment (i8wu) [reply types/index.d.ts]: Importing like that doesn't work, my compiler complains about no declaration file found.

Comment (adidahiya) [reply types/index.d.ts]: hm, ok, can you file an issue for that? I might be able to look into it later

Comment (i8wu) [reply types/index.d.ts]: Should I open up a new issue or is https://github.com/gpbl/react-day-picker/issues/586 good enough? Thank you!

**Comment by alexis-thual** [comment]
Can someone merge this please? :)

**Comment by gpbl** [comment]
Hey thanks for the PR! Are we safe with this? I'm not a TS developer, people were fighting for this kind of issues the last time... should I go and merge?

**Comment by alexis-thual** [comment]
I am not a TS expert but this PR seems quite fair to me; you can go ahead and merge I guess :)

**Comment by adidahiya** [comment]
This is safe; I contributed to the original types on DefinitelyTyped and in this repo. #586 is a separate issue and can be addressed in another PR.

**Comment by gpbl** [comment]
Thanks @adidahiya as always!

**Comment by gpbl** [comment]
Published as [v7.1.0](https://www.npmjs.com/package/react-day-picker).

**Comment by theigor** [comment]
Hi guys - just got latest and getting this error:
```
ERROR in [at-loader] ./node_modules/react-day-picker/types/props.d.ts:177:27
    TS7006: Parameter 'DayModifiers' implicitly has an 'any' type.
```

where line 177 is
```ts
  onDayChange?(day: Date, DayModifiers): void;
```

so this seems like a legitimate issue. Did you mean to do 
```ts
  onDayChange?(day: Date, modifiers:DayModifiers): void;
```

**Comment by theigor** [comment]
By the way, you can avoid things like this in the future by switching your tsconfig to 
```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    ...
  },
  ...
}
```
